---
  - name: MySQL - configure MySQL 5.7 repository
    yum:
      name: https://repo.mysql.com/yum/mysql-5.7-community/el/7/x86_64/mysql57-community-release-el7-10.noarch.rpm
      state: present
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
    register: mysql_result
    until: mysql_result is success
    retries: 3
    delay: 5

  - name: MySQL - install MySQL 5.7 server
    yum:
      name: mysql-community-server
      state: present
    register: mysql_install

  - name: MySQL - upload MySQL 5.7 custom setting /etc/my.cnf
    template:
      src: etc/my.cnf.j2
      dest: /etc/my.cnf
      owner: root
      group: root
      mode: 0644

  - block:
      - name: MySQL - initialize MySQL without a root password
        command: mysqld --initialize-insecure --user=mysql --explicit_defaults_for_timestamp

      - name: MySQL - enable and start MySQL 5.7 server
        systemd:
          name: mysqld
          enabled: yes
          state: started

      - name: MySQL - set root password using shell commands
        shell: mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{mysql_root_password}}'"
    when: mysql_install.changed

  - name: MySQL - enable and start MySQL 5.7 server
    systemd:
      name: mysqld
      enabled: yes
      state: started

  - name: MySQL - install MySQL-python module
    yum:
      name: MySQL-python
      state: present

  - name: MySQL - copy .my.cnf file with root password credentials for Ansible usage
    template:
      src: root/.my.cnf.j2
      dest: /root/.my.cnf
      owner: root
      group: root
      mode: 0600

  - name: MySQL - update root password for all root accounts
    mysql_user:
      name: root
      host: "{{item}}"
      password: "{{mysql_root_password}}"
    with_items:
      - "{{ansible_nodename}}"
      - 127.0.0.1
      - ::1
      - localhost

  - name: ensure anonymous users are not in the database
    mysql_user:
      name: ''
      host: "{{item}}"
      state: absent
    with_items:
      - "{{ansible_nodename}}"
      - 127.0.0.1
      - ::1
      - localhost

  - name: remove the test database
    mysql_db:
      name: test
      state: absent

#  - debug:
#      var: mysql_result


